### PR TITLE
Documentation builds, requirements file, utilities folder

### PR DESCRIPTION
**Pull request by nickrsan**
Hi Jon,

We have a few changes we wanted to incorporate into the Calvin  master - I've been working on it in a fork in our UCM organization. The changes in this actual pull request are minor, except:
 - the addition of an automatic API documentation builder (https://calvin-water.readthedocs.io has the results)
 - fixes the issue with extra newlines in postprocessed results on Windows in Python 3.

But I mostly want to alert you to changes I already merged (I'll plan to use pull requests in the future) in these two commits:

- https://github.com/ucd-cws/calvin/commit/5a912c217f3dd9dc1404a4d7b0aae38cae0aa256 - minor changes that make it easier to turn Calvin into an installable package in the future by making paths always relative to the root of the code rather than relative to the current working directory.
- https://github.com/ucd-cws/calvin/commit/0bf73b5bb82824418d3419cf6dec44ef230273fa - has more consequential changes, including something that breaks Python 2.7 compatibility. It replaces print statements with Python's built-in logging module and writes to the screen and to a file in the current working directory by default. I could fix Python 2.7 compatibility if we think that's important. The logging switch is only implemented right now for the Calvin class and not for the postprocessors.

Please take a look at those previous two commits, and let me know if you want anything changed, and either merge or approve this pull request, at which point I'll merge it. Thank you!

### CODE REVIEW

**Comment by jdherman** [comment]
Hi Nick, you're welcome to merge whatever you need. This all sounds good. 

Side note, I vaguely remember there being a problem with the pyomo solvers expecting python 2.7 only. But that was a few years ago so hopefully that has been updated.

**Comment by msdogan** [comment]
Hi Nick, those changes sound good to me. I am okay with merging.

Jon, you are right. When we first installed pyomo and solvers, it was expecting Python 2.7. But for the worskhop, I requested everyone use Python 3+ and did not have a problem on running CALVIN. Just switched anaconda channel `cachemeorg` to `conda-forge`. The only issue is that latest version of Anaconda and Python is not compatible with pyomo.extras (`conda install -c conda-forge pyomo.extras`) but it turned out that we actually do not need pyomo.extras. Only pyomo and glpk solver is enough to run the model (`conda install -c conda-forge pyomo glpk`). https://anaconda.org/search?q=pyomo

**Comment by wyattarnold** [comment]
Hey Nick, this is great. I had also started a Sphinx build in my fork, but am looking forward to pulling in this merge. I have already worked on several new .rst docs (not just the automodule library) to build up the documentation content.

**Comment by nickrsan** [comment]
@wyattarnold Delayed response on my end, but did you end up committing the docs you wrote up for CALVIN anywhere? It'd be great to get those merged in here! @msdogan is working on quite a few updates and likely a training next year and it could be helpful to reference anything you've written on this. Thanks!

**Comment by wyattarnold** [comment]
@nickrsan I did not work more on the docs. However, I did finish a limited foresight version of CALVIN, which could be useful in certain cases. once the paper is through review, I will let you and @msdogan know.

**Comment by nickrsan** [comment]
OK, sounds good - I'm thinking that will end up being one of our priorities in the near future, to get some better documentation on using CALVIN written up. I know there's some for some use cases, but trying to round it out to address more of the common questions people run into with it will help, I think. Thanks for the response, and I'll be interested in your limited foresight version in the future!

**Pull request merged**
